---
- name: Install python-apt - need move to deps or pre_tasks
  apt:
    name:
      - python-apt
    state: present

- name: get the rpm or apt package facts
  package_facts:
    manager: "apt"

- name: install nginx
  import_tasks: installation.yml
  when: (ansible_facts['packages']['nginx'] is undefined) or (ansible_facts['packages']['nginx'][0].version != docker_version)

- name: Replace nging.conf
  template:
    src=templates/nginx.conf
    dest=/etc/nginx/nginx.conf
